name: quiz_app
description: A new Flutter project.
publish_to: 'none'
version: 1.3.0+4

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^6.4.1
  html_unescape: ^2.0.0
  http: ^0.13.5
  lottie: ^2.3.1
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  wave: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/test.json
